controller_manager:
  ros__parameters:
    update_rate: 100  # 控制频率

    # 关节状态广播器
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 关节轨迹控制器
    dummy_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Joint Trajectory Controller configuration
dummy_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      joint1:
        trajectory: 0.1
        goal: 0.1
      joint2:
        trajectory: 0.1
        goal: 0.1
      joint3:
        trajectory: 0.1
        goal: 0.1
      joint4:
        trajectory: 0.1
        goal: 0.1
      joint5:
        trajectory: 0.1
        goal: 0.1
      joint6:
        trajectory: 0.1
        goal: 0.1

# 关节状态广播器配置
joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    interfaces:
      - position
      - velocity
