# 感知系统配置文件 - Density-aware VoteNet 模型

# 3D 检测器配置
detector:
  name: Density VoteNet-sunrgbd
  type: mmdet3d
  config_file: ~/ros2_ws/src/robotic_follower/model/detection/density_votenet/density_votenet_8xb4-sunrgbd-3d.py
  checkpoint_file: ~/ros2_ws/src/robotic_follower/model/detection/density_votenet/density_votenet_8xb4-sunrgbd-3d.pth
  device: cuda:0
  score_threshold: 0.3
  # ignore_class_names:
  # - cabinet
  # - bed
  # - chair
  # - sofa
  # - table
  # - door
  # - window
  # - bookshelf
  # - picture
  # - counter
  # - desk
  # - curtain
  # - refrigerator
  # - showercurtrain
  # - toilet
  # - sink
  # - bathtub
  # - garbagebin
