perception:
  name: density_votenet
  global: {}

  detector:
    pre: []
    process:
      - type: mmdet3d
        params:
          name: Density VoteNet-sunrgbd
          config_file: ~/ros2_ws/src/robotic_follower/model/detection/density_votenet/density_votenet_8xb4-sunrgbd-3d.py
          checkpoint_file: ~/ros2_ws/src/robotic_follower/model/detection/density_votenet/density_votenet_8xb4-sunrgbd-3d.pth
          device: cuda:0
          score_threshold: 0.3
    post: []

  tracker:
    enabled: false
