perception:
  name: ground_cluster
  global:
    max_distance: 1.4
    ground_percentile: 0.02
    ground_threshold_percent: 0.15

  detector:
    pre:
      - type: radius_filter
        enabled: true
        params:
          max_distance: ${max_distance}
          min_distance: 0.1
      - type: height_filter
        enabled: false
        params:
          threshold: 0.047
          mode: absolute
      - type: voxel_filter
        enabled: true
        params:
          leaf_size: 0.01
      - type: statistical_outlier_removal
        enabled: true
        params:
          k_neighbors: 30
          std_multiplier: 5.1
      - type: ground_estimation
        enabled: false
        params:
          percentile: ${ground_percentile}

    process:
      - type: dbscan_cluster
        params:
          eps: 0.10
          min_samples: 70

    post:
      - type: compute_bbox
      - type: merge_overlapping
        params:
          iou_threshold: 0.2

  tracker:
    enabled: false
